name: TAMZTEST
favicon: null
layout_spectrum: 0.32888891943730414
typography_spectrum: 0.9920740742236376
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#FF6700'
    - '#EBEBEB'
    - '#C0C0C0'
    - '#3A6EA5'
    - '#004E98'
  brandStrength: 0.10328707424923778
  lightness: 0.6352763804607093
  saturation: 0.3022543117403984
  rhythmicContrast: 0.12000758410431445
purpose: []
